export const salesQuotes = [
  "Every 'no' brings you closer to 'yes'.",
  "Success is the sum of small efforts repeated day in and day out.",
  "The difference between try and triumph is just a little umph!",
  "Hustle beats talent when talent doesn't hustle.",
  "Your attitude determines your altitude.",
  "Winners never quit, and quitters never win.",
  "Close deals, not dreams.",
  "Be so good they can't ignore you.",
  "The harder you work, the luckier you get.",
  "Don't wait for opportunity. Create it.",
  "Sales are contingent upon the attitude of the salesman, not the attitude of the prospect.",
  "Success usually comes to those who are too busy to be looking for it.",
  "The key to success is to start before you're ready.",
  "Great things never come from comfort zones.",
  "Dream big. Start small. Act now.",
  "Your only limit is you.",
  "Make today so awesome that yesterday gets jealous.",
  "The secret of getting ahead is getting started.",
  "It's not about having time. It's about making time.",
  "Push yourself, because no one else is going to do it for you.",
  "Success doesn't just find you. You have to go out and get it.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Don't stop when you're tired. Stop when you're done.",
  "Wake up with determination. Go to bed with satisfaction.",
  "Little things make big days.",
  "Work hard in silence. Let success make the noise.",
  "The only way to do great work is to love what you do.",
  "Believe you can and you're halfway there.",
  "Action is the foundational key to all success.",
  "Fortune favors the bold."
];
