project_id = "xuxvqvzkkjgbsqiwjzke"

[functions.sync-metrics]
verify_jwt = false

[functions.send-invite-email]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.finalize-contest]
verify_jwt = false

[functions.admin-set-user-role]
verify_jwt = false

[functions.send-weekly-digest]
verify_jwt = false

[functions.send-scheduled-report]
verify_jwt = false

[functions.send-quote-email]
verify_jwt = false

[functions.notify-new-application]
verify_jwt = false
