-- Add self_generated_deals column to user_metrics table
ALTER TABLE public.user_metrics 
ADD COLUMN self_generated_deals integer DEFAULT 0;

-- Add comment for clarity
COMMENT ON COLUMN public.user_metrics.self_generated_deals IS 'Deals that were self-generated by the sales rep, excluded from lead-to-close ratio calculation';